# Generated by Django 5.1.3 on 2024-11-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceupdate',
            name='admin',
        ),
    ]
